name: Deploy webapi

on:
  workflow_dispatch:
    inputs:
      resourceGroup:
        description: 'リソース グループ名'
        default: 'rg-test-3'
        required: true
        type: string
      webAppName:
        description: 'Web アプリ名'
        default: 'api-test-3'
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_PATH: './src/Api'


    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'
          include-prerelease: true
      
      - name: Build with dotnet
        run: dotnet build ${{ env.APP_PATH }} -c Release
      
      - name: Publish with dotnet
        run: dotnet publish ${{ env.APP_PATH }} -c Release -o ${{ env.APP_PATH }}/webapi
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: webapi
          path: ${{ env.APP_PATH }}/webapi

  deploy:
    runs-on: ubuntu-latest
    needs: build
  
    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: webapi
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapi
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ github.event.inputs.webAppName }}
          slot-name: 'Production'
          package: .
      
      - name: Logout
        run: az logout   
