name: Test

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run test
        run: |
          echo ${{ secrets.AZURE_SUBSCRIPTION_ID }}
